name: "CI: macOS"

on: [ push, pull_request ]

jobs:
  macos-latest-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - uses: lukka/get-cmake@v3.18.3

      - name: Make build directory
        shell: bash
        run: mkdir build

      - name: Build
        working-directory: ./build
        shell: bash
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja
          ninja

      - name: Run tests
        working-directory: ./build/test/unit-tests
        shell: bash
        run: ./UnitTests